15 Replace assets enum with string
WinoGarcia/CryptoPay pull request #16
Opened 2024-02-15 09:28 UTC by WinoGarcia

@BloodShadow174 
Could you kindly perform a code review? This pull request is associated with your most recent [pr](https://github.com/WinoGarcia/CryptoPay/pull/14)

2024-02-15 10:58 UTC, BloodShadow174 commented on CryptoPay/Types/ExchangeRate.cs
I think that changing Asset to a string is only in this object.
There were no problems with others.

2024-02-15 11:01 UTC, BloodShadow174 commented on CryptoPay/Types/ExchangeRate.cs
Regarding the conversion, it would be possible to add a separate static extension class to convert ExchangeRate.Asset and ExchangeRate.Target

2024-02-15 11:04 UTC, BloodShadow174 commented on CryptoPay/Types/ExchangeRate.cs
We can also make a JsonEnum converter and add the Unknown value to Assets

2024-02-20 11:31 UTC, WinoGarcia commented on CryptoPay/Types/ExchangeRate.cs
Using 'Unknown' isn't an option for us because many different apps depend on this library and all types of assets are important to them. If we go this way, we risk losing important data and turning it into 'Unknown'. While I fully understand the practicality of having a finite list of assets, the fact that this is a library compels us to sacrifice convenience for the sake of universality.

2024-02-21 18:42 UTC, BloodShadow174 commented on CryptoPay/Types/ExchangeRate.cs
@WinoGarcia 
Maybe then just add method overloads so as not to break backward compatibility?
In any case, I think that the option with "string" will be a compromise.

2024-02-22 09:26 UTC, WinoGarcia commented on CryptoPay/Types/ExchangeRate.cs
@BloodShadow174 
Unfortunately, backward compatibility will still be broken, even if we overload the methods, but these methods return objects: "Check", "Transfer"... and in them, the assets will be strings. I believe it's better to keep strings everywhere for consistency. 
But I've introduced the auxiliary method AssetsHelper.TryParse to facilitate an easier transition to Assets, which are now represented as string values.

2024-02-22 11:42 UTC, BloodShadow174 requested changes

2024-02-22 11:42 UTC, BloodShadow174 commented on CryptoPay/Types/Assets.cs
It seems to me that it’s worth leaving the same numerical values here, because for example, my old Assets.BTC in the database has value 0, and Assets.USD value is 101. Assets.Unknown can be made -1. Or somehow warn users about changing this enumeration...

2024-02-22 13:35 UTC, WinoGarcia commented on CryptoPay/Types/Assets.cs
@BloodShadow174 
You're correct. I've reverted those changes.

2024-02-22 13:39 UTC, BloodShadow174 commented on CryptoPay/Types/Assets.cs
@WinoGarcia 
Would it make sense to number all Assets at once to avoid confusion in the future?
```
BTC =0 ,
TON = 1,
```
etc..

2024-02-22 14:04 UTC, WinoGarcia commented on CryptoPay/Types/Assets.cs
@BloodShadow174 
Yes, that would be more correct. I've fixed it.

2024-02-22 21:59 UTC, BloodShadow174 approved these changes

2024-02-22 21:59 UTC, BloodShadow174 approved these changes

2024-02-22 22:23 UTC, BloodShadow174 commented on CryptoPay/Types/Assets.cs
> +    /// </summary>уа
Typo

2024-02-23 12:06 UTC, merged